// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0g9Ciy2MZxTq-N9txO0Wi2Z3YBzEBhgc',
    appId: '1:768435514779:web:e9dab74434d90169a4053e',
    messagingSenderId: '768435514779',
    projectId: 'epollutioncontrol-caa2a',
    authDomain: 'epollutioncontrol-caa2a.firebaseapp.com',
    storageBucket: 'epollutioncontrol-caa2a.appspot.com',
    measurementId: 'G-QY371RYJ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohRvx-xAZlbDC0JetcKMtLQ8UVnWXrjI',
    appId: '1:768435514779:android:3400309ee3275561a4053e',
    messagingSenderId: '768435514779',
    projectId: 'epollutioncontrol-caa2a',
    storageBucket: 'epollutioncontrol-caa2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmMo3qysuvQeIMI_1UkKTEfDcBq4rOnE',
    appId: '1:768435514779:ios:89e5b11e414b7cd3a4053e',
    messagingSenderId: '768435514779',
    projectId: 'epollutioncontrol-caa2a',
    storageBucket: 'epollutioncontrol-caa2a.appspot.com',
    iosBundleId: 'com.example.epc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmMo3qysuvQeIMI_1UkKTEfDcBq4rOnE',
    appId: '1:768435514779:ios:e7e2406550fdc79ba4053e',
    messagingSenderId: '768435514779',
    projectId: 'epollutioncontrol-caa2a',
    storageBucket: 'epollutioncontrol-caa2a.appspot.com',
    iosBundleId: 'com.example.epc.RunnerTests',
  );
}
